{
 "title": "Registry exporter",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "registry",
    "label": "Registry",
    "query": {
     "query": "label_values(registry_size,registry)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total registry size",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(registry_size{registry=~\"$registry\"})",
     "legendFormat": "{{registry}}"
    }
   ]
  },
  {
   "title": "Total  size (sum of all images)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(registry_tag{registry=~\"$registry\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Repositories",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(registry_repo{registry=~\"$registry\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# Tags",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(registry_tag{registry=~\"$registry\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Largest images",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(5,sum(registry_repo{registry=~\"$registry\"}) by (repo) / count(registry_tag{registry=~\"$registry\"}) by (repo))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Images per architecture",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "count(registry_tag{registry=~\"$registry\",mediaType=~\".*image.*\"}) by (arch)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Images per Os",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 6, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count(registry_tag{registry=~\"$registry\",os!=\"\"}) by (os)",
     "legendFormat": "Os"
    }
   ]
  },
  {
   "title": "Images per mediaType",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {
     "expr": "count(registry_tag{registry=~\"$registry\",mediaType!=\"\"}) by (mediaType)",
     "legendFormat": "Helm chart"
    }
   ]
  },
  {
   "title": "Size per repository",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(registry_repo{registry=~\"$registry\"}) by (repo)",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Size per repository (top10)",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 15, "x": 9, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(10,sum(registry_repo{registry=~\"$registry\"}) by (repo))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tags per repository",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 9, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(registry_tag{registry=~\"$registry\"}) by (repo)",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "Tags per repository (top 10)",
   "type": "barchart",
   "gridPos": { "h": 15, "w": 15, "x": 9, "y": 38 },
   "targets": [
    {
     "expr": "topk(10,count(registry_tag{registry=~\"$registry\"}) by (repo))",
     "legendFormat": "{{repo}}"
    }
   ]
  },
  {
   "title": "All Helm charts",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "registry_tag{registry=~\"$registry\",mediaType=~\".*helm.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All OCI images",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 53 },
   "targets": [
    {
     "expr": "registry_tag{registry=~\"$registry\",mediaType=~\".*oci.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "All Docker images",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 53 },
   "targets": [
    {
     "expr": "registry_tag{registry=~\"$registry\",mediaType=~\".*docker.*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}